# -*- coding: utf-8 -*-
"""NumPyBasicArrayOperations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K39be1pDgQDrYvQUR9jattD9WnFgwk0T

**Maestría en Inteligencia Artificial y Analítica de Datos**

Curso: *Programación para Analítica Descriptiva y Predictiva*

* Semestre: Enero-Junio 2026
* Profesor: Dr. Vicente García Jiménez
* Alumno: Ricardo Solano Monje
* Matrícula: 266221
* Unidad 1
* Práctica 3: Creación de un arreglo y operaciones básicas.
* Objetivo de la práctica: Usar NumPy para crear arreglos y realizar algunas operaciones básicas.
* Realizado por: Ricardo Solano Monje.

# NumPy: *Basic Array Operations*

### Creación de un arreglo y operaciones básicas.

* Crea un arreglo unidimensional de 20 elementos con valores aleatorios entre 1 y 100. Luego, realiza las siguientes operaciones:

* Encuentra el valor máximo del arreglo,

* Encuentra el valor mínimo del arreglo,

* Calcula la media del arreglo,

* Suma 10 a cada elemento del arreglo.
"""

import numpy as np
print("NumPy version:", np.__version__)

"""### 1. Create a one-dimensional array of 20 elements with random values between 1 and 100"""

# Create array with random integers between 1 and 100 (inclusive)
np.random.seed(42)  # Setting seed for reproducibility
array1d = np.random.randint(1, 101, size=20)

print("Original Array values:")
print(array1d)
print(f"\nArray shape: {array1d.shape}")# shape return a tuple, the trailing comma signifies that it is a 1-item tuple.
# print(f"Array type: {array1d.dtype}")

"""## *Carry out the following Operations:*

* *1: Find the maximum value in the array*
"""

maxValue = np.max(array1d)
print(f"1. Maximum value: {maxValue}")
print(f"   Index Position of max value: {np.argmax(array1d)}")

"""* *2: Find the minimum value in the array*"""

minValue = np.min(array1d)
print(f"2. Minimum value: {minValue}")
print(f"   Index Position of min value: {np.argmin(array1d)}")

"""* *3: Calculate the mean of the array*"""

meanValue = np.mean(array1d) #straight forward solution using NumPy function
print(f"   Getting Mean value using NumPy's mean function:")
print(f"3. Mean value: {meanValue:.2f}")
print(f"   Performing Mean value in three steps:")
print(f"   I.   Sum of all elements: {np.sum(array1d)}")
print(f"   II.  Number of elements: {len(array1d)}")
print(f"   III. Mean value performed in three steps = Sum of all elements/Number of elements = {np.sum(array1d)/len(array1d):.2f} ")

"""* *4: Add 10 to each element of the array*"""

# For Broadcasting the operation to all elements of the array, just add 10, NumPy will do the job
array1dPlus10 = array1d + 10  # NumPy performs the addition of 10 to all elements
print(f"NumPy will perform the addition of 10 to all elements of the array")
print("4. Array after adding 10 to each element:")
print(f"Original array:\n {array1d}")
print(f"Plus 10 array:\n {array1dPlus10}")

